version: "2"
services:
  web:
    build: .
    ports:
    - "80:80"
    # volumes: 
    # - .:/usr/routes/index
    depends_on:
    - mongo
  mongo:
    container_name: mongoo
    image: mongoo
    ports:
    - "27017:27017"
    volumes:
        - data-volume:/data/db
volumes:
    data-volume: